# Generated by Django 4.2.1 on 2023-05-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='facerecognitionresult',
            name='student_attend',
        ),
        migrations.AddField(
            model_name='facerecognitionresult',
            name='student_attend',
            field=models.ManyToManyField(to='management.face'),
        ),
    ]
