# Generated by Django 4.2.1 on 2023-06-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clazz',
            name='place',
            field=models.CharField(default='T5, Tiet 4-6', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clazz',
            name='schedule',
            field=models.CharField(default='D6-201', max_length=500),
            preserve_default=False,
        ),
    ]
