# Generated by Django 4.2.1 on 2023-06-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_attendance_clazz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='session',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
