# Generated by Django 4.2.1 on 2023-06-08 08:49

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_student_session_delete_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimage',
            name='image',
            field=models.FileField(upload_to=main_app.models.Student.get_image_path),
        ),
    ]
