# Generated by Django 4.2.1 on 2023-06-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_attendancerecord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimage',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
