# Generated by Django 4.2.1 on 2023-06-08 10:21

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_studentimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimage',
            name='image',
            field=models.ImageField(upload_to=main_app.models.Student.get_image_path),
        ),
    ]
